"""modifies_climate

Revision ID: 0bd8a58bcbff
Revises: ee74d7f5c8dd
Create Date: 2025-06-24 22:07:20.179408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd8a58bcbff'
down_revision = 'ee74d7f5c8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('windspeed', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('winddirection', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('weathercode', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climate', schema=None) as batch_op:
        batch_op.drop_column('weathercode')
        batch_op.drop_column('winddirection')
        batch_op.drop_column('windspeed')

    # ### end Alembic commands ###
