"""add_table_climate

Revision ID: ee74d7f5c8dd
Revises: 78bc64d6763d
Create Date: 2025-06-16 11:55:52.945280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee74d7f5c8dd'
down_revision = '78bc64d6763d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciudad_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('climate')
    # ### end Alembic commands ###
